{{- if .Values.configmap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  {{- if .Values.jobs }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
  {{- end }}
  labels:
    app: {{ .Release.Name }}
    env: {{ .Values.environment }}
data:
{{-  range $key, $value := .Values.configmap }}
    {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
