{{ if .Values.service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}
    env: {{ .Values.environment }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.targetName }}
      protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ .Release.Name }}
    env: {{ .Values.environment }}
{{ end }}